# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.

# Sets up the jupyter notebooks to use the local graph repository
egeria:
  repositoryType: "local-graph-repository"
