# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.

# Example of showing how to use a specific version of egeria. This can include snapshots

egeria:
  version: "4.0"
image:
  egeria:
    tag: 4.0
    pullPolicy: Always
imageDefaults:
  tag: 4.0
jupyter:
  gitTagForNotebooks: main
