# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.

# Example configuring nodeports - note this list may be incomplete
# this allows connection to the pods directly using a known IP of the node running k8s
service:
  type: NodePort
  nodeport:
    jupyter: 32188
    core: 32080
    datalake: 32081
    dev: 32082
    factory: 32083
    ui: 32443
    presentation: 32091
