# Copyright © 2023 Atruvia AG <opensource@atruvia.de> as contributor to the ODPi Egeria project.
---
apiVersion: v2
name: egeria-lineage
description: A Helm chart for the egeria integration lineage event driven connector sample
type: application
version: 3.15.0
appVersion: "3.15"
icon: https://raw.githubusercontent.com/odpi/egeria/99016e77167fa30dcfade809b061358a92a59973/assets/img/egeria.png
keywords:
  - odpi, egeria, base, simple, event, driven, lineage, sample, atruvia
sources:
  - https://github.com/odpi/egeria-connector-integration-lineage-event-driven-sample
home: https://github.com/odpi/egeria-connector-integration-lineage-event-driven-sample
maintainers:
  - name: Jürgen Hemelt
    email: juergen.hemelt@atruvia.de
  - name: Tunç Taylan Turunç
    email: tunc_taylan.turunc@atruvia.de
dependencies:
  - name: egeria-base
    version: 3.15.0
    # TODO change to official chart repository
    # repository: https://odpi.github.io/egeria-charts
    repository: "file://../egeria-base"
    condition: egeria-base.enabled