# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the ODPi Egeria project.
site_name: Egeria Kubernetes Helm Charts
docs_dir: docs
site_dir: site

site_description: Helm charts for deploying Egeria to Kubernetes
copyright: "License: <a href='https://creativecommons.org/licenses/by/4.0/'>CC BY 4.0</a>, &copy; 2018-2021 contributors to the Egeria project."
repo_name: odpi/egeria-charts
repo_url: https://github.com/odpi/egeria-charts
site_url: https://odpi.github.io/egeria-charts/site
edit_uri: ""

nav:
  - About: index.md
  - Introduction:
      - intro/k8s.md
      - intro/helm.md
  - Available Charts:
      - charts/lab.md
      - charts/base.md
  - Related projects:
      - more/operator.md
  - Contribute:
      - contribute/devguide.md    

theme:
  name: material
  language: en
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
#    - navigation.instant
    - navigation.top
#    - toc.integrate
  palette:
    - scheme: default
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  logo: assets/images/egeria-header.png

extra_css:
  - assets/stylesheets/egeria.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/odpi/egeria
      name: Egeria on GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/odpi
      name: Egeria on Docker
    - icon: fontawesome/brands/medium
      link: https://medium.com/tag/egeria
      name: Egeria on Medium
    - icon: fontawesome/brands/slack
      link: https://lfaifoundation.slack.com/archives/C01F40J2XA8
      name: Egeria on Slack

markdown_extensions:
  - admonition
  - attr_list
  - abbr
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

