# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
{{ if .Values.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: {{ include "egeria-base.name" . }}
    helm.sh/chart: {{ include "egeria-base.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: egeria-rbac
  name: {{ template "egeria-base.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}