# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.

# Sample to setup cluster monitoring on Red Hat Openshift 4.11+
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      volumeClaimTemplate:
        spec:
          storageClassName: fast
          volumeMode: Filesystem
          resources:
            requests:
              storage: 40Gi
