# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "MkDocs"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # We need all history - we we can later switch to gh-pages
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # Ensure we have the latest version of ghp_import 
      - run: pip install mkdocs-material ghp_import
      # Manually run the mkdocs build (config is set to use 'site' to publish to)
      - run: mkdocs -v build
        working-directory: ./site
      # mkdocs doesn't allow a subdir to be published to, so run ghp-import directly
      # All content will go to 'site' and will leave root content untouched
      - run: ghp-import site -m 'Updated mkdocs' -p -x site -n
        working-directory: ./site
